# Generated by Django 4.1 on 2023-03-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Profile',
        ),
    ]
