# Generated by Django 4.1 on 2023-04-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_admin_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название картины')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Описание картины')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации картины')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название галереи')),
                ('description', models.CharField(max_length=50, verbose_name='Описание галереи')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teacher_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название галереи')),
                ('description', models.CharField(max_length=50, verbose_name='Описание галереи')),
                ('status', models.CharField(choices=[('PRIVATE', 'Закрытый'), ('INNER', 'Внутренний'), ('PUBLIC', 'Открытый')], max_length=50, verbose_name='Видимость галереи')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
