# Generated by Django 4.1 on 2023-04-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_gallery',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='Описание галереи'),
        ),
        migrations.AlterField(
            model_name='student_gallery',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='teacher_gallery',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='Описание галереи'),
        ),
        migrations.AlterField(
            model_name='teacher_gallery',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название галереи'),
        ),
    ]
