# Generated by Django 4.1 on 2023-04-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_student_gallery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название картины')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Описание картины')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации картины')),
                ('student_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.student_gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название картины')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Описание картины')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации картины')),
                ('teacher_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.teacher_gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
