# Generated by Django 4.1 on 2023-05-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_public_gallery_alter_student_gallery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_gallery',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание галереи'),
        ),
        migrations.AlterField(
            model_name='public_gallery',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='public_picture',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание картины'),
        ),
        migrations.AlterField(
            model_name='public_picture',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название картины'),
        ),
        migrations.AlterField(
            model_name='student_gallery',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание галереи'),
        ),
        migrations.AlterField(
            model_name='student_gallery',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='student_picture',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание картины'),
        ),
        migrations.AlterField(
            model_name='student_picture',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название картины'),
        ),
        migrations.AlterField(
            model_name='teacher_gallery',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание галереи'),
        ),
        migrations.AlterField(
            model_name='teacher_gallery',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='teacher_picture',
            name='description',
            field=models.CharField(max_length=650, null=True, verbose_name='Описание картины'),
        ),
        migrations.AlterField(
            model_name='teacher_picture',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название картины'),
        ),
    ]
