# Generated by Django 4.1 on 2023-03-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_profile_first_name_and_more'),
        ('educational_app', '0003_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher_profile', verbose_name='Автор курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(blank=True, to='users.study_group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название дисциплины'),
        ),
    ]
