# Generated by Django 4.1 on 2023-03-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0005_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
