# Generated by Django 4.1 on 2023-04-04 19:54

import django.core.validators
from django.db import migrations, models
import educational_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0007_alter_course_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(upload_to=educational_app.models.get_lecture_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
