# Generated by Django 4.1 on 2023-04-04 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import educational_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0008_alter_lecture_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=educational_app.models.get_test_file_path, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.course', verbose_name='Дисциплина')),
            ],
        ),
    ]
