# Generated by Django 4.1 on 2023-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0009_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название теста'),
            preserve_default=False,
        ),
    ]
