# Generated by Django 4.1 on 2023-04-06 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import educational_app.models
import educational_app.file_methods

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_profile_first_name_and_more'),
        ('educational_app', '0010_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=educational_app.file_methods.get_test_attempt_file_path, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student_profile', verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test', verbose_name='Тест')),
            ],
        ),
    ]
