# Generated by Django 4.1 on 2023-04-09 17:24

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0011_test_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(default='3d 2:20:10', verbose_name='Длительность теста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='Срок сдачи'),
            preserve_default=False,
        ),
    ]
