# Generated by Django 4.1 on 2023-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0012_test_duration_test_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[(1, 'PROCESS'), (2, 'DONE')], default='PROCESS', max_length=50, verbose_name='Статус теста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_attempt',
            name='status',
            field=models.CharField(choices=[(1, 'CHECK'), (2, 'DENIED'), (3, 'ACCESS')], default='CHECK', max_length=50, verbose_name='Статус решения теста'),
            preserve_default=False,
        ),
    ]
