# Generated by Django 4.1 on 2023-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0014_alter_test_status_alter_test_attempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'PROCESS'), ('DONE', 'DONE')], max_length=50, verbose_name='Статус теста'),
        ),
        migrations.AlterField(
            model_name='test_attempt',
            name='status',
            field=models.CharField(choices=[('CHECK', 'CHECK'), ('DENIED', 'DENIED'), ('ACCESS', 'ACCESS')], max_length=50, verbose_name='Статус решения теста'),
        ),
    ]
