# Generated by Django 4.1 on 2023-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0015_alter_test_status_alter_test_attempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'В процессе'), ('DONE', 'Завершено')], max_length=50, verbose_name='Статус теста'),
        ),
        migrations.AlterField(
            model_name='test_attempt',
            name='status',
            field=models.CharField(choices=[('CHECK', 'Проверяется'), ('DENIED', 'Отказано'), ('ACCESS', 'Принято')], max_length=50, verbose_name='Статус решения теста'),
        ),
    ]
