# Generated by Django 4.1 on 2023-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0016_remove_test_expiration_date_alter_test_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'В процессе'), ('DONE', 'Завершено'), ('CLOSED', 'Закрыт')], max_length=50, verbose_name='Статус теста'),
        ),
    ]
