# Generated by Django 4.1 on 2023-04-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0019_mark_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_test',
            name='test_attempt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_app.test_attempt', verbose_name='Попытка выполнения теста'),
        ),
    ]
