# Generated by Django 4.1 on 2023-04-30 14:49

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0021_rename_mark_test_test_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата теста'),
            preserve_default=False,
        ),
    ]
