# Generated by Django 4.1 on 2023-05-04 14:56

import django.core.validators
from django.db import migrations, models
import educational_app.file_methods


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0022_test_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(upload_to=educational_app.file_methods.get_lecture_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx'])]),
        ),
    ]
