# Generated by Django 4.1 on 2023-05-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0023_alter_lecture_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Текст вопроса')),
                ('mark', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='test_mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='test_mark',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test_mark',
            name='test_attempt',
        ),
        migrations.RemoveField(
            model_name='test',
            name='file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='qwq', max_length=150, verbose_name='Название теста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикация теста'),
        ),
        migrations.DeleteModel(
            name='Test_Attempt',
        ),
        migrations.DeleteModel(
            name='Test_Mark',
        ),
        migrations.AddField(
            model_name='test_question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test', verbose_name='Тест'),
        ),
    ]
