# Generated by Django 4.1 on 2023-05-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_profile_first_name_and_more'),
        ('educational_app', '0024_test_question_remove_test_mark_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test_question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения теста')),
                ('status', models.CharField(choices=[('CHECK', 'Проверяется'), ('DENIED', 'Отказано'), ('ACCESS', 'Принято')], max_length=50, verbose_name='Статус попытки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student_profile', verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Attempt_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test_answer', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test_question', verbose_name='Тестовый вопрос')),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.test_attempt', verbose_name='Тестовая попытка')),
            ],
            options={
                'unique_together': {('test_attempt', 'question')},
            },
        ),
    ]
