# Generated by Django 4.1 on 2023-05-13 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0025_test_answer_test_attempt_test_attempt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_attempt',
            name='mark',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
