# Generated by Django 4.1 on 2023-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0026_test_attempt_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_attempt_answer',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
