# Generated by Django 4.1 on 2023-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_profile_first_name_and_more'),
        ('educational_app', '0027_alter_test_attempt_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задания')),
                ('code_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата задания')),
                ('status', models.CharField(choices=[('PROCESS', 'В процессе'), ('DONE', 'Завершено'), ('CLOSED', 'Закрыт')], max_length=50, verbose_name='Статус задания')),
                ('mark', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.course', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CHECK', 'Проверяется'), ('DENIED', 'Отказано'), ('ACCESS', 'Принято')], max_length=50, verbose_name='Статус решения задания')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения задания')),
                ('mark', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student_profile', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.task', verbose_name='Задание')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Attempt_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('task_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.task_attempt', verbose_name='Попытка задания')),
            ],
        ),
    ]
