# Generated by Django 4.1 on 2023-05-24 00:52

from django.db import migrations, models
import educational_app.file_methods


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0028_task_task_attempt_task_attempt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_attempt',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_attempt_file',
            name='file',
            field=models.FileField(upload_to=educational_app.file_methods.get_task_file_path),
        ),
    ]
