# Generated by Django 4.1 on 2023-03-11 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_app', '0003_alter_course_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 28, 35, 517797))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.course')),
            ],
        ),
    ]
