# Generated by Django 4.1 on 2023-03-12 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0004_alter_course_author_alter_course_description_and_more'),
        ('informing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_announce',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_app.course', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='course_announce',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 21, 7, 39, 880382), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='course_announce',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='course_announce',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок объявления'),
        ),
    ]
