# Generated by Django 4.1 on 2023-03-12 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0003_alter_course_announce_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_announce',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 21, 10, 34, 913933), verbose_name='Дата публикации'),
        ),
    ]
