# Generated by Django 4.1 on 2023-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0005_alter_course_announce_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_announce',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
