# Generated by Django 4.1 on 2023-03-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_profile_first_name_and_more'),
        ('informing_app', '0006_alter_course_announce_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок объявления')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin_profile', verbose_name='Автор объявления')),
            ],
        ),
        migrations.CreateModel(
            name='News_Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher_profile', verbose_name='Автор новости')),
            ],
        ),
    ]
