# Generated by Django 4.1 on 2023-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0007_system_announce_news_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_announce',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='news_announce',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок объявления'),
        ),
    ]
