# Generated by Django 4.1 on 2023-05-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0008_alter_news_announce_text_alter_news_announce_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_announce',
            name='text',
        ),
    ]
