# Generated by Django 4.1 on 2023-05-04 14:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0009_remove_news_announce_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_announce',
            name='html',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
