# Generated by Django 4.1 on 2023-05-04 17:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0010_news_announce_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_announce',
            name='html',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
