# Generated by Django 4.1 on 2023-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing_app', '0011_alter_news_announce_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_announce',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='news_announce',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='system_announce',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок объявления'),
        ),
    ]
